[package]
name = "bluex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.79"
bindgen = { version = "0.66.1", features = ["runtime"] }

[dependencies]
near-base = { path = "../../common/near-base" }

async-std = { workspace = true }

log = { workspace = true }
once_cell = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
mac_address = { workspace = true }

enumflags2 = { workspace = true }
